Repository fivetran/dbt_fivetran_utils, pull requests merged in 2021-11, with the labels that each got.

#50 Bugfix/snowflake json extract
  CHANGELOG.md
  macros/json_extract.sql
Labels: bug

#49 Expand union_data to allow multiple packges to leverage it with different variables
  .gitignore
  macros/source_relation.sql
  macros/union_data.sql
Labels: enhancement

#51 Release/v0.2.9
  .gitignore
  CHANGELOG.md
  README.md
  dbt_project.yml
  integration_tests/dbt_project.yml
  macros/json_extract.sql
  macros/source_relation.sql
  macros/union_data.sql
Labels: bug, enhancement
